/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	crdexamplecomv1 "github.com/murali-bashyam/crdexample/pkg/apis/crd.example.com/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStoragePools implements StoragePoolInterface
type FakeStoragePools struct {
	Fake *FakeCrdV1
	ns   string
}

var storagepoolsResource = schema.GroupVersionResource{Group: "crd.example.com", Version: "v1", Resource: "storagepools"}

var storagepoolsKind = schema.GroupVersionKind{Group: "crd.example.com", Version: "v1", Kind: "StoragePool"}

// Get takes name of the storagePool, and returns the corresponding storagePool object, and an error if there is any.
func (c *FakeStoragePools) Get(ctx context.Context, name string, options v1.GetOptions) (result *crdexamplecomv1.StoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(storagepoolsResource, c.ns, name), &crdexamplecomv1.StoragePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexamplecomv1.StoragePool), err
}

// List takes label and field selectors, and returns the list of StoragePools that match those selectors.
func (c *FakeStoragePools) List(ctx context.Context, opts v1.ListOptions) (result *crdexamplecomv1.StoragePoolList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(storagepoolsResource, storagepoolsKind, c.ns, opts), &crdexamplecomv1.StoragePoolList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &crdexamplecomv1.StoragePoolList{ListMeta: obj.(*crdexamplecomv1.StoragePoolList).ListMeta}
	for _, item := range obj.(*crdexamplecomv1.StoragePoolList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested storagePools.
func (c *FakeStoragePools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(storagepoolsResource, c.ns, opts))

}

// Create takes the representation of a storagePool and creates it.  Returns the server's representation of the storagePool, and an error, if there is any.
func (c *FakeStoragePools) Create(ctx context.Context, storagePool *crdexamplecomv1.StoragePool, opts v1.CreateOptions) (result *crdexamplecomv1.StoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(storagepoolsResource, c.ns, storagePool), &crdexamplecomv1.StoragePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexamplecomv1.StoragePool), err
}

// Update takes the representation of a storagePool and updates it. Returns the server's representation of the storagePool, and an error, if there is any.
func (c *FakeStoragePools) Update(ctx context.Context, storagePool *crdexamplecomv1.StoragePool, opts v1.UpdateOptions) (result *crdexamplecomv1.StoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(storagepoolsResource, c.ns, storagePool), &crdexamplecomv1.StoragePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexamplecomv1.StoragePool), err
}

// Delete takes name of the storagePool and deletes it. Returns an error if one occurs.
func (c *FakeStoragePools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(storagepoolsResource, c.ns, name), &crdexamplecomv1.StoragePool{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStoragePools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(storagepoolsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &crdexamplecomv1.StoragePoolList{})
	return err
}

// Patch applies the patch and returns the patched storagePool.
func (c *FakeStoragePools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *crdexamplecomv1.StoragePool, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(storagepoolsResource, c.ns, name, pt, data, subresources...), &crdexamplecomv1.StoragePool{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdexamplecomv1.StoragePool), err
}
