apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagepools.crd.example.com
spec:
  group: crd.example.com
  names:
    kind: StoragePool
    listKind: StoragePoolList
    plural: storagepools
  scope: Namespaced
  version: v1
  openAPIV3Schema:
      properties:
        spec:
          properties:
            failureDomain:
                type: string
            quota:
                type: integer
  subresources:
    status: {}
